* Installation
  - Include paths to this folder within your ~/.bashrc file
  - Include required paths for DEFAULT_BIN_PATH and DEFAULT_PYTHON_PATH

* Configuration
  configuration is done through the config.py file.

  currently, the paths for berrypi and for python are hardcoded within
  this file due to the nature of the current users environment. This
  should be changed in later developments to accomodate all users if
  it is a requirement.

  Before running, DEFAULT_BIN_PATH and DEFAULT_PYTHON_PATH values
  within config.py should be set to legitimate values

  DEFAULT_BIN_PATH - should be exactly the same as your BerryPi
  directory root where all of the code is being stored.

  example:

  DEFAULT_BIN_PATH='~/share/BerryPI/'

  DEFAULT_PYTHON_PATH - should be the path to the current python
  distribution.  NOTE: please also include the python command which is
  also being used, with a space.

  example:

  DEFAULT_PYTHON_PATH='/usr/bin/python2.7 '
  
  NOTE: the space at the end of python2.7 (this is required).

  for further configuration options when running berrypi, run 

  python ~/BerryPI/berrypi -h

  to get a list of prefix options.

* Dependencies
  - WIEN2k (tested against 11.1 Release 05/04/2011)
  - WIEN2WANNIER (tested against 0.92)
  - Python (tested against 2.7.3)
  - NumPy (tested against 1.6.2)
  
* File Descriptions
** win2nnkp.py
   Generate the nearest neighbour list of k points
** mmn2pathphase.py
   Calculate the Berry phase for a particuler direction	
*  Calculation of the Berry Phase
   After getting pathphase(x,y,z), obtain each value is divided by PI Make
   sure that the values are within the [0, 2*PI] ex. -3.2 == 0.8pi
   normalizing.Then they are presented as Electronic phase/(2*pi)
** berrypi
   The main file to run. It automates the 'entire' berry process
** submoduleProcess.py
   File used for general shell interaction through python.
** parsing.py
   Includes functions for parsing certain wien2k and w2w files. The
   data being parsed from these files is used to calculate the
   information needed
** errorCheck.py
   Includes exception handling and background checks on files. Pretty
   barren right now.
** config.py
   *Important* this file is used to change how the
   berryPyParseAutomation works and needs to be pre-configured on
   first use
** calculations.py
   Includes the necessary classes to carry out the remaining
   calculations at the end of the automation run

* Limitation
The present version is restricted to cases when the lattice vectors correspond to cartesian directions. For example, the zinc-blend or NaCl structures should be regarded as an 8 atom cell instead of the conventional 2 atom basis.

* To Do
** Non collinear lattice vectors
Extendting the capability of "BerryPI" to computing of polrization
for structures with non collinear lattice vectors
** Band by band decomposition
Provide analysis of contribution from individual electronic bands (or their range) to the electronic polarization. The present version is enables calculation of the Berry phase for a given band range (-b switch), but more testing need to be performed.
	
* Tutorials
** Tutorial 1 - For Spontaneous polarization calculation of BaTiO3	
** Tutorial 2 - For Born Effective Charges of GaAs