* Installation
  - make sure all the correct paths are set in your .bashrc. You need
    to have paths to *mmn2pathphase.py*, *win2nnkp.py*, wein2k, w2w,
    etc.
* Configuration
  configuration is done through the berryPyConfiguration.py file. You
  can either include new configurations in the berryPyConfiguration.py
  file itself, or append the configurations into the
  berryPyConfigAutomationList variable. 

  There is an example in berryPyConfiguration.py to work with.

  New:

  You can now run berryPyRunAutomation.py standalone and just provide
  the structure name and structure path. It has also been modified to
  only perform the last polarization calculation if you would like to
  run your own simulation scripts.

* Dependencies
  - python 2.7
  - numpy 1.6+
  - wien2wannier (found out version)
  - WIEN2k 11.1

* File Descriptions
** berryPyRunAutomation.py
   The main file to run. It automates the 'entire' berry process
** berryPySubmoduleProcess.py
   File used for general shell interaction through python.
** berryPyParsing.py
   Includes functions for parsing certain wien2k and w2w files. The
   data being parsed from these files is used to calculate the
   information needed
** berryPyErrorCheck.py
   Includes exception handling and background checks on files. Pretty
   barren right now.
** berryPyConfiguration.py
   *Important* this file is used to change how the
   berryPyParseAutomation works and needs to be pre-configured on
   first use
** berryPyCalculations.py
   Includes the necessary classes to carry out the remaining
   calculations at the end of the automation run
* Calculation of the Berry Phase
  - After getting pathphase(x,y,z), obtain each value divided PI Make
    sure that the values are within the [0, 2*PI] ex. -3.2 == 0.8pi
    normalizing
  - sum(values) / num(values)
  - Next, we need to calculate the eletronic polarization in the Z
    direction Pel_z = electron charge(C) / (Volume (m^3 from bohr ^ 3) * berry Phase
    (PI form) * Lattice vector(cz) (Z-direction in metres from bohr)

    NOTE: might need to do a absolute (vector multiplication)

  - Next, we need to calculate the eletronic polarization in the Y
    direction Pel_y = electron charge(C) / (Volume (m^3 from bohr ^ 3) * berry Phase
    (PI form) * Lattice vector (by) (Y-direction in metres from bohr) BR2_DIR in *.outputd

  - etc.... x direction

  - converting from bhor to m^3

  - After we have calculated electron polarization, we calculate ionic
    polarization Pion_z = electron charge(C) / Volume (m^3 from
    bohr) * Lattice Constant (z direction in m from bohr) * (#valence
    electrons in atom 1 * Z direction of atom 1) + ... + (#valence
    electroncs in atoms 1 * Z direction of atom N)

    NOTE: MULT atoms require you do the calculation for that
    iteration * MULT + it's particular coordinates

  - for *.outputst 
    take total charge per spin (1) + total charge per spin (2) - total core-charge for each atom

  - Pion_x, Pion_y....

  - Next, we get the polarization by ionic polarization + the electron polarization
    P_x = Pion_x + Pel_x .... etc
    
* TODO listing [100%]
  - [X] Fix .struct file to parse element name into atom listing
  - [X] Fix outputd to only include the information necessary to carry
    out the calculation
